name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Accept Google licenses
      run: echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build with Buildozer
      run: |
        buildozer android debug
