name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_NDK_HOME: /opt/android-ndk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download Android SDK tools
      run: |
        sudo mkdir -p /opt/android-sdk
        sudo mkdir -p /opt/android-ndk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O android-sdk.zip
        unzip android-sdk.zip -d /opt/android-sdk/cmdline-tools
        mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest

    - name: Install SDK packages
      run: |
        echo "Installing SDK packages"
        yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529" "cmdline-tools;latest" "tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build the APK
      run: |
        buildozer -v android debug
      env:
        ANDROIDSDK: /opt/android-sdk
        ANDROIDNDK: /opt/android-ndk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyApp-APK
        path: |
          .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/myapp/build/outputs/apk/debug/*.apk
